title: 'I speak here {^_^}'
email: mehabhalodiya@gmail.com
description: 'I speak here {^_^}'
baseurl: ""
url: "https://mehabhalodiya.github.io"
twitter_username: mehabhalodiya
github_username:  mehabhalodiya

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

# Build settings
plugins:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-paginate

sass:
    sass_dir: _sass
    style: :compressed
